print("Master version")
print("Feature login version")
print("New GitHub practice")
print("Changed from GitHub")
print("Local developer change")
print("Remote developer change")
print("Feature branch GitHub practice")